Added more bullshit terms
mourner/bullshit.js pull request #184
Opened 2022-08-17 00:44 UTC by jayhawker6

Such as NFT, Bleeding edge, and a few other additions.

2022-08-19 17:26 UTC, mourner requested changes

2022-08-19 17:26 UTC, mourner commented on src/terms.js
> +    'merge(er)?',
Perhaps you meant this?

```suggestion
    'merger?',
```

2022-08-19 17:26 UTC, mourner commented on src/terms.js
> +    'bleeding edge',
To capture `bleeding-edge`:

```suggestion
    'bleeding.edge',
```

2022-08-21 01:39 UTC, jayhawker6 commented
Changes Commited.

2022-08-26 20:51 UTC, mourner approved these changes

2022-08-26 20:51 UTC, merged